# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 100504f8148c0cb61f4f21cd282256355766d97d6b4b16a2b67bb244b1b1caeb77db670e31befdf2edfc58ada03c939bb0c0a78a4ebc39167788bd53dcd8fff3

test:
  secret_key_base: 320cffcc694508e55154d050f6b9fcc06f842bc61bee65394a64d55b51873f7575d715a158599e9a23fe7ef1f7a7f8432faef9891a539d785b747ca64f9499b5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
